#! /usr/bin/env python3

import argparse
import shutil

parser = argparse.ArgumentParser()
parser.add_argument("name")

args = parser.parse_args()

shutil.copytree(
    "../template",
    args.name,
)
